# specify the version of docker-compose
version: "3.8"

services:
  web:
    depends_on:
      - server
    build:
      context: ./frontend
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/yarn.lock
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  server:
    depends_on:
      - db
    build:
      context: ./backend
    environment:
      - PORT=3000
      - HOST=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:password@db:5432/expense_tracker
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_USERNAME=vivienne.johnston@ethereal.email
      - SMTP_PASSWORD=TWeBtbRyjP64UN1ZPZ
      - EMAIL_FROM=support@expensetracker.com
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/yarn.lock
          action: rebuild
        - path: ./backend
          target: /app
          action: sync 
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expense_tracker
volumes:
  db-data:

